dist: xenial
language: php
php:
- '7.3'
- '7.0'
- '5.6'

addons:
  apt:
    packages:
    - php7.3

before_install:
- echo "phar.readonly = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
- tests/makephar.sh
