matrix:
  variant:
    - "debian"
    - "alpine"
  platform:
    - linux/arm64

platform: ${platform}

clone:
  git:
    when:
      event:
        - tag
        - push
    image: woodpeckerci/plugin-git:v1.5.0
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: true

pipeline:
  build:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/madelineproto
      dockerfile: "tests/dockerfiles/Dockerfile.${variant}"
      platforms: ${platform}
      tag: next-${variant}
      cache_from: danog/madelineproto:next-${variant}
      cache_to: type=inline
    when:
      event:
        - tag
        - push
  
  alias:
    image: docker:cli
    secrets: [docker_username, docker_password]
    environment:
      - docker_username=${docker_username}
      - docker_password=${docker_password}
    commands:
      - docker login -p "$docker_password" -u "$docker_username"
      - docker pull danog/madelineproto:next-debian
      - docker tag danog/madelineproto:next-debian danog/madelineproto:next
      - docker push danog/madelineproto:next
    when:
      event:
        - tag
        - push
