matrix:
  variant:
    - "debian"
    - "alpine"
  platform:
    - linux/arm64

platform: ${platform}

clone:
  git:
    when:
      event:
        - tag
        - push
    image: woodpeckerci/plugin-git:v1.5.0
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: true

pipeline:
  build:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/madelineproto
      dockerfile: "tests/dockerfiles/Dockerfile.${variant}"
      platforms: ${platform}
      tag: next-${variant}
      cache_from: danog/madelineproto:next-${variant}
      cache_to: type=inline
    when:
      event:
        - tag
        - push

  alias:
    image: docker:cli
    secrets: [docker_username, docker_password]
    environment:
      - DUSER=${docker_username}
      - DPASS=${docker_password}
    commands:
      - tests/alias.sh
    when:
      event:
        - tag
        - push
