matrix:
  variant:
    - "debian"
    - "alpine"
  platform:
    - linux/arm64

platform: ${platform}

clone:
  git:
    when:
      event:
        - tag
        - push
    image: woodpeckerci/plugin-git:v1.5.0
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: true

pipeline:
  variants:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/madelineproto
      dockerfile: "tests/dockerfiles/Dockerfile.${variant}"
      platforms: ${platform}
      tag: next-${variant}
      cache_from: danog/madelineproto:next-${variant}
      cache_to: type=inline
    when:
      event:
        - tag
        - push
  
  variants-tag:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/madelineproto
      dockerfile: "tests/dockerfiles/Dockerfile.${variant}"
      platforms: ${platform}
      tag: ${variant}
      cache_from: danog/madelineproto:next-${variant}
      cache_to: type=inline
    when:
      event:
        - tag

  alias:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/madelineproto
      dockerfile: "tests/dockerfiles/Dockerfile.debian"
      platforms: ${platform}
      tag: next
      cache_from: danog/madelineproto:next-${variant}
      cache_to: type=inline
    when:
      event:
        - tag
        - push
      matrix:
        variant: "debian"

  alias-tag:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/madelineproto
      dockerfile: "tests/dockerfiles/Dockerfile.debian"
      platforms: ${platform}
      tag: latest
      cache_from: danog/madelineproto:next-${variant}
      cache_to: type=inline
    when:
      event:
        - tag
      matrix:
        variant: "debian"