matrix:
  variant:
    - "debian"
    - "alpine"
  platform:
    - linux/arm64

clone:
  git:
    when:
      event:
        - tag
    image: woodpeckerci/plugin-git:v1.5.0
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: true

pipeline:
  build:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/madelineproto
      dockerfile: "tests/dockerfiles/Dockerfile.${variant}"
      platforms: ${platform}
      tag: latest-${variant}
    when:
      event:
        - tag
  
  alias:
    image: docker:cli
    secrets: [docker_username, docker_password]
    commands:
      - docker login -u "$docker_username" -p "$docker_password"
      - docker pull danog/madelineproto:latest-alpine
      - docker tag danog/madelineproto:latest-alpine danog/madelineproto:latest
      - docker push danog/madelineproto:latest
    when:
      event:
        - tag
        - push