matrix:
  variant:
    - "debian"
    - "alpine"
  platform:
    - linux/arm64

clone:
  git:
    when:
      event:
        - tag
        - push
    image: woodpeckerci/plugin-git:v1.5.0
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: true

pipeline:
  docker:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/madelineproto
      dockerfile: "tests/dockerfiles/Dockerfile.${variant}"
      platforms: ${platform}
      tag: latest-${variant}
    when:
      event:
        - tag
        - push
  
  docker-latest:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/madelineproto
      dockerfile: "tests/dockerfiles/Dockerfile.alpine"
      platforms: ${platform}
      tag: latest
    when:
      event:
        - tag
        - push