pipeline:
  alias:
    image: docker:cli
    secrets: [docker_username, docker_password]
    environment:
      - DUSER=${docker_username}
      - DPASS=${docker_password}
    commands:
      - docker login -p "$DUSER" -u "$DPASS"
      - docker pull danog/madelineproto:next-alpine
      - docker pull danog/madelineproto:next-debian
      - docker pull danog/madelineproto:next
      - docker tag danog/madelineproto:next-alpine danog/madelineproto:alpine
      - docker tag danog/madelineproto:next-debian danog/madelineproto:debian
      - docker tag danog/madelineproto:next danog/madelineproto:latest
      - docker push danog/madelineproto:alpine
      - docker push danog/madelineproto:debian
      - docker push danog/madelineproto:latest
    when:
      event:
        - tag

depends_on:
  - "build-docker"