matrix:
  platform:
    - linux/arm64

clone:
  git:
    when:
      event:
        - tag
    image: woodpeckerci/plugin-git:v1.5.0
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: true

pipeline:
  alias:
    image: docker:cli
    secrets: [docker_username, docker_password]
    commands:
      - docker login -u "$docker_username" -p "$docker_password"
      - docker pull danog/madelineproto:next-alpine
      - docker pull danog/madelineproto:next-debian
      - docker pull danog/madelineproto:next
      - docker tag danog/madelineproto:next-alpine danog/madelineproto:alpine
      - docker tag danog/madelineproto:next-debian danog/madelineproto:debian
      - docker tag danog/madelineproto:next danog/madelineproto:latest
    when:
      event:
        - tag
        - push

depends_on:
  - "build-docker"