matrix:
  php:
    - "8.1"
  platform:
    - linux/aarch64

labels:
  platform: ${platform}

clone:
  git:
    when:
      event:
        - tag
        - push
        - pull_request
    image: woodpeckerci/plugin-git:2.1.0
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: true

steps:
  test:
    group: test
    image: danog/madelineproto:next
    when:
      event:
        - tag
        - push
    secrets:
      - API_ID
      - API_HASH
      - BOT_TOKEN
      - DEST
    commands:
      - apk add bash
      - tests/test.sh phpunit
    
  test_pr:
    group: test
    image: danog/madelineproto:next
    when:
      event:
        - pull_request
    commands:
      - apk add bash
      - tests/test.sh phpunit-light

  cs:
    group: test
    image: danog/madelineproto:next
    when:
      event:
        - pull_request
        - tag
        - push
    commands:
      - apk add bash
      - tests/test.sh cs
  
  psalm:
    group: test
    image: danog/madelineproto:next
    when:
      event:
        - pull_request
        - tag
        - push
    commands:
      - apk add bash
      - tests/test.sh psalm
  
  handshake:
    group: test
    image: danog/madelineproto:next
    when:
      event:
        - pull_request
        - tag
        - push
    commands:
      - apk add bash
      - tests/test.sh handshake
