matrix:
  php:
    - "8.1"
  platform:
    - linux/arm64

platform: ${platform}

clone:
  git:
    when:
      event:
        - tag
        - push
        - pull_request
    image: woodpeckerci/plugin-git:v1.5.0
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: true

pipeline:
  test:
    group: test
    image: danog/madelineproto:next
    when:
      event:
        - tag
        - push
        - pull_request
    secrets:
      - GITHUB_TOKEN
      - API_ID
      - API_HASH
      - BOT_TOKEN
      - DEST
    environment:
      - PHP_VERSION=${php}
      - PLATFORM=${platform}
      - TAG=${CI_COMMIT_TAG}
    commands:
      - apk add bash
      - /bin/bash -e tests/test.sh

depends_on:
  - build-docker
