name: build
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.0'
    name: PHP ${{ matrix.php }} build
    env:
      PHP_CS_FIXER_IGNORE_ENV: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          fetch-depth: 0

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, sockets, gmp, curl, xml, json
          coverage: none
          ini-values: phar.readonly=0

      - name: Build
        run: |
          tests/makephar.sh
